In [2]:
level = {
    'intern': {
        'bonus': 5
    },
    'staff': {
        'bonus': 10
    },
    'manager': {
        'bonus': 15
    },
    'director': {
        'bonus': 20
    }
}

employee_data = [
    {
        'name': 'Rudi',
        'level': 'staff',
        'salary': 7500000
    },
    {
        'name': 'Rita',
        'level': 'intern',
        'salary': 1000000
    },
    {
        'name': 'Asep',
        'level': 'manager',
        'salary': 12000000
    },
    {
        'name': 'Ricky',
        'level': 'manager',
        'salary': 13500000
    },
    {
        'name': 'Lisa',
        'level': 'staff',
        'salary': 8500000
    },
       {
        'name': 'Imam',
        'level': 'intern',
        'salary': 1050000
    },
    {
        'name': 'Haryo',
        'level': 'director',
        'salary': 35000000
    }
]

In [3]:
# Data level dan persentase bonus
level = {
    'intern': {
        'bonus': 5
    },
    'staff': {
        'bonus': 10
    },
    'manager': {
        'bonus': 15
    },
    'director': {
        'bonus': 20
    }
}

# Data karyawan
employee_data = [
    {'name': 'Rudi', 'level': 'staff', 'salary': 7500000},
    {'name': 'Rita', 'level': 'intern', 'salary': 1000000},
    {'name': 'Asep', 'level': 'manager', 'salary': 12000000},
    {'name': 'Ricky', 'level': 'manager', 'salary': 13500000},
    {'name': 'Lisa', 'level': 'staff', 'salary': 8500000},
    {'name': 'Imam', 'level': 'intern', 'salary': 1050000},
    {'name': 'Haryo', 'level': 'director', 'salary': 35000000}
]

# Kamus untuk menyimpan hasil bonus setiap karyawan
employee_bonus = {}

# Menghitung bonus setiap karyawan
for employee in employee_data:
    nama = employee['name']  # Nama karyawan
    level_karyawan = employee['level']  # Level karyawan
    gaji = employee['salary']  # Gaji karyawan
    persentase_bonus = level[level_karyawan]['bonus']  # Mendapatkan persentase bonus berdasarkan level
    bonus = gaji * persentase_bonus / 100  # Menghitung bonus
    employee_bonus[nama] = bonus  # Menyimpan hasil bonus dalam kamus

# Menampilkan hasil
print(employee_bonus)

{'Rudi': 750000.0, 'Rita': 50000.0, 'Asep': 1800000.0, 'Ricky': 2025000.0, 'Lisa': 850000.0, 'Imam': 52500.0, 'Haryo': 7000000.0}